# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ef7FQnwJIyK4qYa1l_qfk4mb1urOyFd0
"""

import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[0, 2],
              [4, 6]])

vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print(vertical_stack)
print(horizontal_stack)

common_elements = np.intersect1d(A, B)
common_elements

result = A[np.where((A<3) & (A>0))]
result

mask = (iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)
iris_2d[mask]

import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_df = df.iloc[::20][['Manufacturer', 'Model' , 'Type']]
filtered_df

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print(df['Min.Price'])
print(df['Max.Price'])

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rows = df[df.sum(axis=1) > 100]
rows